"""Add weekly archive table

Revision ID: 06112e2b1618
Revises: e7943b047909
Create Date: 2025-10-30 16:37:04.196593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '06112e2b1618'
down_revision: Union[str, None] = 'e7943b047909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weeklyarchive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('week_end', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weeklyarchive_player_name'), 'weeklyarchive', ['player_name'], unique=False)
    op.create_index(op.f('ix_weeklyarchive_week_end'), 'weeklyarchive', ['week_end'], unique=False)
    op.create_index(op.f('ix_weeklyarchive_week_start'), 'weeklyarchive', ['week_start'], unique=False)
    op.alter_column('player', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_player_email'), 'player', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_email'), table_name='player')
    op.alter_column('player', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_weeklyarchive_week_start'), table_name='weeklyarchive')
    op.drop_index(op.f('ix_weeklyarchive_week_end'), table_name='weeklyarchive')
    op.drop_index(op.f('ix_weeklyarchive_player_name'), table_name='weeklyarchive')
    op.drop_table('weeklyarchive')
    # ### end Alembic commands ###

